# Generated by Django 4.1.2 on 2022-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceF', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cImage', models.URLField()),
            ],
        ),
    ]
